add `fa_IR` / [job, person, lorem, phone_number]
jiro4989/faker pull request #75
Opened 2022-01-11 06:37 UTC by hamidb80

Hey, I added `fa_IR` support for few modules

2022-01-11 06:38 UTC, hamidb80 commented
I think it's better to store datasets in separated files btw.

2022-01-11 14:49 UTC, jiro4989 commented
Thank you.

2022-01-11 15:08 UTC, jiro4989 commented
Please implements `src/faker/provider/internet/internet_fa_IR.nim`.
Because, `proc email*(f: Faker): string` ([here](https://github.com/hamidb80/faker/blob/926693ca950fb90e7b7d8ebac6a87f6b6d778beb/src/faker/provider/internet.nim#L65-L74)) returns illegal email.

ex:

```
بهزاد@example.org
الهام@yahoo.co.jp
مسعود@example.com
```

see: [Internet Message Format > Address Specification - RFC5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4)

2022-01-11 15:09 UTC, jiro4989 requested changes
Please add test code here

https://github.com/hamidb80/faker/blob/master/tests/test1.nim#L12

```nim
let locales = ["en_US", "ja_JP", "fa_IR"]
```

2022-01-11 15:10 UTC, jiro4989 requested changes
Please implements `src/faker/provider/internet/internet_fa_IR.nim`.
Because, `proc email*(f: Faker): string` ([here](https://github.com/hamidb80/faker/blob/926693ca950fb90e7b7d8ebac6a87f6b6d778beb/src/faker/provider/internet.nim#L65-L74)) returns illegal email.

ex:

```
بهزاد@example.org
الهام@yahoo.co.jp
مسعود@example.com
```

see: [Internet Message Format > Address Specification - RFC5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4)

2022-01-11 17:26 UTC, hamidb80 commented
I think it's OK now

2022-01-11 22:27 UTC, jiro4989 requested changes

2022-01-11 22:27 UTC, jiro4989 commented on src/faker/provider/internet/internet_fa_IR.nim
> +    else: ""
hmm...?
Compile error was occured in Nim 1.0.x, and 1.2.x.

Please check this [CI Log](https://github.com/jiro4989/faker/runs/4782151899?check_suite_focus=true#step:4:10) and fix it.

2022-01-12 12:09 UTC, jiro4989 approved these changes
LGTM 👍 

![LGTM](https://image.lgtmoon.dev/95028)

2022-01-12 12:10 UTC, merged